security:
  oauth2:
    client:
      clientId: clientId
      clientSecret: clientSecret
      accessTokenUri: https://sandbox.login.telia.io/realms/telia/protocol/openid-connect/token
      userAuthorizationUri: https://sandbox.login.telia.io/realms/telia/protocol/openid-connect/auth
    resource:
      userInfoUri: https://sandbox.login.telia.io/realms/telia/protocol/openid-connect/userinfo

server:
  port: 8080
  context-path: /demo